# baseURL: "https://www.vinoteqa.com/"
languageCode: "en-us"

title: "Vinoteqa - Your Winecellar Always in Your Pocket"
themesDir: "themes/"
theme: "up-business-theme-vinoteqa"

# googleAnalytics: ""

summaryLength: 20

params:
  logo: "logo.png"
  title: "Vinoteqa - Your Winecellar Always in Your Pocket"
  description: "Vinoteqa simplifies wine inventory management for high end restaurants and wine bars. Our user-friendly software streamlines operations and automomatizes the generation of your wine list, freeing you to focus on perfecting the dining experience and wine research."
  images: 
    - "images/bg.jpg"


  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # linkedin: "https://www.linkedin.com/company/vinoteqa/"

  location:
    - "South Tyrol, Italy"

  contact:
    - "vinoteqa@gmail.com"

  copyright: "© 2023 Vinoteqa All Rights Reserved"

menus:
  buttons:
    - name: "Book a FREE Demo"
      url: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ0EXnISWhh5nFfAEy1ajA0T4LPs3C947WLoZLfNsRSSCKpwdHoZBUlmQHUOWzDRXhIA2OGn9n6e"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
