# baseURL: "https://www.vinoteqa.com/"
languageCode: "en-us"

themesDir: "themes/"
theme: "up-business-theme-vinoteqa"

# googleAnalytics: ""

summaryLength: 20

defaultContentLanguage: en
languages:
  en:
    languageCode: en-us
    languageDirection: ltr
    languageName: English
    weight: 0
    contentDir: content/en
    title: "Vinoteqa - Your Winecellar Always in Your Pocket"
    params:
      description: "Vinoteqa simplifies wine inventory management for high end restaurants and wine bars. Our user-friendly software streamlines operations and automomatizes the generation of your wine list, freeing you to focus on perfecting the dining experience and wine research."
      location:
        title: "Location"
        content: "South Tyrol, Italy"
      contact:
        title: "Contact Us"
        content: "[vinoteqa@gmail.com](mailto:vinoteqa@gmail.com)"
    menus:
      buttons:
        - name: "Book a FREE Demo"
          url: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ0EXnISWhh5nFfAEy1ajA0T4LPs3C947WLoZLfNsRSSCKpwdHoZBUlmQHUOWzDRXhIA2OGn9n6e"
          weight: 5
          pre: "btn btn-primary text-light"
  de:
    languageCode: de-de
    languageDirection: ltr
    languageName: Deutsch
    weight: 2
    contentDir: content/de
    title: "Vinoteqa - Dein Weinkeller - Jederzeit & Überall"
    params:
      description: "Vinoteqa simplifies wine inventory management for high end restaurants and wine bars. Our user-friendly software streamlines operations and automomatizes the generation of your wine list, freeing you to focus on perfecting the dining experience and wine research."
      location:
        title: "Location"
        content: "Südtirol, Italien"
      contact:
        title: "Kontakt"
        content: "[vinoteqa@gmail.com](mailto:vinoteqa@gmail.com)"
    menus:
      buttons:
        - name: "Gratis DEMO"
          url: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ0EXnISWhh5nFfAEy1ajA0T4LPs3C947WLoZLfNsRSSCKpwdHoZBUlmQHUOWzDRXhIA2OGn9n6e"
          weight: 5
          pre: "btn btn-primary text-light"
  it:
    languageCode: it-it
    languageDirection: ltr
    languageName: Italiano
    weight: 1
    contentDir: content/it
    title: "Vinoteqa - La tua cantina alla portata di un dito"
    params:
      description: "Vinoteqa semplifica e ottimizza la gestione dell'inventario vino per ristoranti ed enoteche di alta qualità. Il nostro software intuitivo e avanzato semplifica le procedure operative e la creazione della carta vini, consentendoti di concentrarti esclusivamente sull'eccellenza dell'esperienza offerta ai tuoi ospiti e sulla continua ricerca dei vini più prestigiosi e distintivi."
      location:
        title: "Dove siamo"
        content: "Alto Adige, Italia"
      contact:
        title: "Contatti"
        content: "[vinoteqa@gmail.com](mailto:vinoteqa@gmail.com)"
    menus:
      buttons:
        - name: "Prenota una Demo gratuita"
          url: "https://calendar.google.com/calendar/appointments/schedules/AcZssZ0EXnISWhh5nFfAEy1ajA0T4LPs3C947WLoZLfNsRSSCKpwdHoZBUlmQHUOWzDRXhIA2OGn9n6e"
          weight: 5
          pre: "btn btn-primary text-light"

# default params
params:
  logo: "logo.png"
  images:
    - "images/bg.jpg"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # linkedin: "https://www.linkedin.com/company/vinoteqa/"

  copyright: "© 2023 Vinoteqa - All Rights Reserved"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
