# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/lib/cfg/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# List available actions
actions:
    @just --list

# Build the frontend
build:
    nix build .#wcms-landing

# Run the frontend
run:
    nix run .#wcms-landing
