name = "Up Business Theme for Vinoteqa"
license = "MIT"
licenselink = "https://gitlab.com/writeonlyhugo/up-business-theme/-/blob/master/LICENSE"
description = "A clean and modern landing page website inspired by clean and modern illustrations."

homepage = "https://gitlab.com/writeonlyhugo/up-business-theme/"
demosite = "https://writeonlyhugo.gitlab.io/up-business-demo/"

tags = ["blog", "responsive", "personal", "light", "bootstrap", "features", "landing", "company", "modern"]
features = []
min_version = "0.92.2"

[author]
  name = "Gabriele De Candido"
